<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Company>DishNet Africa</Company>
    <Product>DishNet Secure Connect</Product>
    <Copyright>© DishNet Africa. Powered by WireGuard® (a registered trademark of Jason A. Donenfeld).</Copyright>
    <Version>0.4.0</Version>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
