// Package firewall renders the hub's nftables policy from the desired access
// rules and applies it atomically. The generated table is default-deny: a
// packet arriving from a VPN peer is forwarded only if an explicit rule
// allows it. Nothing user-supplied is ever interpolated as text — every
// field is a validated netip value or integer.
package firewall

import (
	"context"
	"fmt"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Rule allows traffic from one VPN address to a destination.
type Rule struct {
	CustomerID int64
	Label      string // comment only; sanitised
	Src        netip.Addr
	Dst        netip.Prefix
	Proto      string // tcp | udp | icmp
	Ports      []int  // empty for icmp
}

// Spec is everything the generator needs.
type Spec struct {
	Interface string
	Rules     []Rule
	// HubAddresses: addresses of the hub inside the VPN pools; peers may ping them.
	HubAddresses []netip.Addr
}

const TableName = "dishnet"

// Render produces the complete nftables file. Output is deterministic
// (rules sorted) so it can be diffed and golden-tested.
func Render(s Spec) (string, error) {
	iface := s.Interface
	if iface == "" {
		iface = "wg0"
	}
	if !validIfname(iface) {
		return "", fmt.Errorf("firewall: invalid interface name %q", iface)
	}
	rules := append([]Rule(nil), s.Rules...)
	sort.SliceStable(rules, func(i, j int) bool {
		if rules[i].CustomerID != rules[j].CustomerID {
			return rules[i].CustomerID < rules[j].CustomerID
		}
		if rules[i].Src != rules[j].Src {
			return rules[i].Src.Less(rules[j].Src)
		}
		if rules[i].Dst.Addr() != rules[j].Dst.Addr() {
			return rules[i].Dst.Addr().Less(rules[j].Dst.Addr())
		}
		return rules[i].Proto < rules[j].Proto
	})

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by dishnet-vpnd — DO NOT EDIT. Applied atomically with `nft -f`.\n")
	fmt.Fprintf(&b, "table inet %s\ndelete table inet %s\n", TableName, TableName) // declare-then-delete makes the file idempotent
	fmt.Fprintf(&b, "table inet %s {\n", TableName)

	// Forwarding: everything that enters from, or leaves to, the VPN interface
	// is handled by our chains. Other interfaces are untouched.
	fmt.Fprintf(&b, "\tchain forward {\n")
	fmt.Fprintf(&b, "\t\ttype filter hook forward priority filter; policy accept;\n")
	fmt.Fprintf(&b, "\t\tiifname %q goto vpn_from_peer\n", iface)
	fmt.Fprintf(&b, "\t\toifname %q goto vpn_to_peer\n", iface)
	fmt.Fprintf(&b, "\t}\n")

	// Traffic initiated by a peer. Default deny.
	fmt.Fprintf(&b, "\tchain vpn_from_peer {\n")
	fmt.Fprintf(&b, "\t\tct state invalid drop\n")
	fmt.Fprintf(&b, "\t\tct state established,related accept\n")
	for _, r := range rules {
		line, err := renderRule(r)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "\t\t%s\n", line)
	}
	fmt.Fprintf(&b, "\t\tcounter drop comment \"dishnet default deny\"\n")
	fmt.Fprintf(&b, "\t}\n")

	// Traffic from any other interface (e.g. the public NIC) towards a peer:
	// only replies to connections the peer opened.
	fmt.Fprintf(&b, "\tchain vpn_to_peer {\n")
	fmt.Fprintf(&b, "\t\tct state established,related accept\n")
	fmt.Fprintf(&b, "\t\tcounter drop comment \"dishnet inbound to peer denied\"\n")
	fmt.Fprintf(&b, "\t}\n")

	// Traffic from a peer to the hub itself: ping only.
	fmt.Fprintf(&b, "\tchain input {\n")
	fmt.Fprintf(&b, "\t\ttype filter hook input priority filter; policy accept;\n")
	fmt.Fprintf(&b, "\t\tiifname %q goto vpn_to_hub\n", iface)
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tchain vpn_to_hub {\n")
	fmt.Fprintf(&b, "\t\tct state established,related accept\n")
	if len(s.HubAddresses) > 0 {
		addrs := make([]string, 0, len(s.HubAddresses))
		for _, a := range s.HubAddresses {
			addrs = append(addrs, a.String())
		}
		sort.Strings(addrs)
		fmt.Fprintf(&b, "\t\tip daddr { %s } icmp type echo-request accept\n", strings.Join(addrs, ", "))
	}
	fmt.Fprintf(&b, "\t\tcounter drop comment \"dishnet peer to hub denied\"\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "}\n")
	return b.String(), nil
}

func renderRule(r Rule) (string, error) {
	if !r.Src.IsValid() || !r.Src.Is4() {
		return "", fmt.Errorf("firewall: rule has invalid source %v", r.Src)
	}
	if !r.Dst.IsValid() || !r.Dst.Addr().Is4() {
		return "", fmt.Errorf("firewall: rule has invalid destination %v", r.Dst)
	}
	comment := sanitiseComment(fmt.Sprintf("c%d %s", r.CustomerID, r.Label))
	dst := r.Dst.Masked().String()
	if r.Dst.Bits() == 32 {
		dst = r.Dst.Addr().String()
	}
	switch r.Proto {
	case "tcp", "udp":
		if len(r.Ports) == 0 {
			return "", fmt.Errorf("firewall: %s rule without ports", r.Proto)
		}
		ports := make([]string, 0, len(r.Ports))
		for _, p := range r.Ports {
			if p < 1 || p > 65535 {
				return "", fmt.Errorf("firewall: invalid port %d", p)
			}
			ports = append(ports, strconv.Itoa(p))
		}
		sort.Strings(ports)
		return fmt.Sprintf("ip saddr %s ip daddr %s %s dport { %s } accept comment %q", r.Src, dst, r.Proto, strings.Join(ports, ", "), comment), nil
	case "icmp":
		return fmt.Sprintf("ip saddr %s ip daddr %s icmp type echo-request accept comment %q", r.Src, dst, comment), nil
	}
	return "", fmt.Errorf("firewall: unsupported protocol %q", r.Proto)
}

func sanitiseComment(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == ' ' || r == '-' || r == '_' || r == '.' {
			b.WriteRune(r)
		}
	}
	out := b.String()
	if len(out) > 60 {
		out = out[:60]
	}
	return out
}

func validIfname(s string) bool {
	if s == "" || len(s) > 15 {
		return false
	}
	for _, r := range s {
		if !(r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '-' || r == '_' || r == '.') {
			return false
		}
	}
	return true
}

// Applier writes and loads the rule set.
type Applier interface {
	Apply(ctx context.Context, rendered string) error
}

// NFT writes the file to Path and runs `nft -f Path`. The nft binary path is
// fixed; nothing from the request reaches argv.
type NFT struct {
	Path   string
	Binary string // default /usr/sbin/nft
}

func (n *NFT) Apply(ctx context.Context, rendered string) error {
	bin := n.Binary
	if bin == "" {
		bin = "/usr/sbin/nft"
	}
	if err := os.MkdirAll(filepath.Dir(n.Path), 0o755); err != nil {
		return err
	}
	tmp := n.Path + ".tmp"
	if err := os.WriteFile(tmp, []byte(rendered), 0o644); err != nil {
		return err
	}
	// Syntax check first so a bad file never replaces the good one.
	if out, err := exec.CommandContext(ctx, bin, "-c", "-f", tmp).CombinedOutput(); err != nil {
		os.Remove(tmp)
		return fmt.Errorf("firewall: nft check failed: %v: %s", err, strings.TrimSpace(string(out)))
	}
	if err := os.Rename(tmp, n.Path); err != nil {
		return err
	}
	if out, err := exec.CommandContext(ctx, bin, "-f", n.Path).CombinedOutput(); err != nil {
		return fmt.Errorf("firewall: nft apply failed: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// Fake records what would have been applied.
type Fake struct {
	Applied  []string
	FailNext error
}

func (f *Fake) Apply(ctx context.Context, rendered string) error {
	if f.FailNext != nil {
		err := f.FailNext
		f.FailNext = nil
		return err
	}
	f.Applied = append(f.Applied, rendered)
	return nil
}

func (f *Fake) Last() string {
	if len(f.Applied) == 0 {
		return ""
	}
	return f.Applied[len(f.Applied)-1]
}
