package api

import (
	"embed"
	"net/http"
)

// The customer manual, generated by tools/build-manual.py from
// docs/manual/customer-setup-guide.md and embedded so every hub serves the
// version it was built with: /guide (HTML) and /guide.pdf.
//
//go:embed manual/guide.html manual/guide.pdf
var manualFS embed.FS

func RegisterManual(mux *http.ServeMux) {
	mux.HandleFunc("GET /guide", func(w http.ResponseWriter, r *http.Request) {
		b, _ := manualFS.ReadFile("manual/guide.html")
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("Referrer-Policy", "no-referrer")
		_, _ = w.Write(b)
	})
	mux.HandleFunc("GET /guide.pdf", func(w http.ResponseWriter, r *http.Request) {
		b, _ := manualFS.ReadFile("manual/guide.pdf")
		w.Header().Set("Content-Type", "application/pdf")
		w.Header().Set("Content-Disposition", `inline; filename="DishNet-Secure-Connect-Customer-Setup-Guide.pdf"`)
		w.Header().Set("X-Content-Type-Options", "nosniff")
		_, _ = w.Write(b)
	})
}
